### ISSUE TITLE
Email invites not working

### ISSUE THREAD

**Issue by samschultzponsys** [kanbn/kan#96]
Describe the bug
I am finding email invites are not working, I am able to send email to login but not for initial member adds, also of note I can only login via email I am not seeing an option to change my password.

Environment (please complete the following information):

OS: Unraid Docker Compose
Browser Chrome
Additional context

my compose:
services:
web:
image: ghcr.io/kanbn/kan:latest
container_name: kan-web
ports:
- "6921:3000"
networks:
- kan-network
environment:
NEXT_PUBLIC_BASE_URL: https://kan.redacted.com/
BETTER_AUTH_SECRET: 4yVFT7rredactedHmT
POSTGRES_URL: postgresql://kan:redacted21@postgres:5432/kan_db
BETTER_AUTH_TRUSTED_ORIGINS: https://kan.redacted.com/
NEXT_PUBLIC_ALLOW_CREDENTIALS: "false"
#SMTP (optional)
SMTP_HOST: smtp.purelymail.com
SMTP_PORT: 465
SMTP_SECURE: "true"
SMTP_USER: [kan@infraredacted.com](mailto:kan@infraredacted.com)
SMTP_PASSWORD: hrajhtmdredacteduzyl
EMAIL_FROM: [kan@infra.redacted.com](mailto:kan@infra.redacted.com)
NEXT_PUBLIC_DISABLE_SIGN_UP: "true"
depends_on:
- postgres
volumes:
- /mnt/user/appdata/kan/kan_config:/app/config
restart: unless-stopped

postgres:
image: postgres:15
container_name: kan-db
environment:
POSTGRES_DB: kan_db
POSTGRES_USER: kan
POSTGRES_PASSWORD: redacted
ports:
- "5432:5432"
volumes:
- /mnt/user/appdata/kan/kan_postgres_data:/var/lib/postgresql/data
restart: unless-stopped
networks:
- kan-network

networks:
kan-network:

**Comment by hjball** [comment]
Are you getting any error logs when attempting to invite another user?

You'll need to update your env to allow email/password login:

```
NEXT_PUBLIC_ALLOW_CREDENTIALS: "true"
```

**Comment by daksteter** [comment]
Having a similar issue, where is the logging stored?

**Comment by hjball** [comment]
You can view your container logs with:

```
docker logs -f kan-web
```

**Comment by daksteter** [comment]
Oh ok sure yeah I had checked that already and there's no activity when I click the Invite button.  The dialog remains after clicking Invite, and I can only close it with the X control

**Comment by samschultzponsys** [comment]
I don't get an error, the invite dialogue just seems to not work but as soon as I close it the invite shows it's there, I don't get any email received on the invited email address.

**Comment by hjball** [comment]
Any logs in your browser console? @samschultzponsys @daksteter 

Does the network request resolve?

**Comment by hjball** [comment]
We might need to add more logging to get to the bottom of this

**Comment by samschultzponsys** [comment]
Ill test it again soon I am sorry I am not familiar with the logging for this tool yet.

**Comment by daksteter** [comment]
> Any logs in your browser console? [@samschultzponsys](https://github.com/samschultzponsys) [@daksteter](https://github.com/daksteter)
> 
> Does the network request resolve?

Firefox network tools shows this 500 response when I click the Invite button:

![Image](https://github.com/user-attachments/assets/202f15b7-7cfb-4531-9cbd-d2761e6944a9)

The console shows:

![Image](https://github.com/user-attachments/assets/fd3ff409-e63f-4d13-9725-04247b7a4eb2)

The container logs don't report the 500 error that I can see

[stack.txt](https://github.com/user-attachments/files/21030827/stack.txt)

I also attached the entire result message from the Console tab that looks to have the stack trace, this seems to be the primary error:

_TRPCClientError: Failed to send magic link to user with email --email removed--
​​
cause: undefined
​​
columnNumber: 368_


Another screenshot of the console with details expanded:

![Image](https://github.com/user-attachments/assets/1b20c5bc-3646-414b-826f-15226aa6cc59)

**Comment by xitriy87** [comment]
I get same error when try to invite member. https://kanbn.tss.local/api/trpc/member.invite?batch=1 Internal error 500. Docker container logs speaks nothing about this error.

**Comment by DeadFrostt** [comment]
Currently facing the same issue, logs are completely blank.

**Comment by hjball** [comment]
Thanks for all the info everyone - I'm looking into this as priority -> https://kan.bn/kan/roadmap/atk2puc7qtun

**Comment by samschultzponsys** [comment]
No worries thank you again

**Comment by maltsev-gorskij** [comment]
Same here. Please add verbose logging

**Comment by hjball** [comment]
Please can someone retry and post the container logs

**Comment by daksteter** [comment]
My log results:

```
> dotenv -e ../../.env -- "next" "start"

   ▲ Next.js 15.3.4
   - Local:        http://localhost:3000
   - Network:      http://172.18.0.3:3000

 ✓ Starting...
- event [next-runtime-env] read environment variables prefixed with 'NEXT_PUBLIC_' from process.env.
- ready [next-runtime-env] wrote browser runtime environment variables to '/app/apps/web/public/__ENV.js'.
{"level":30,"time":1752212490331,"pid":94,"hostname":"25302d92f23d","name":"console","msg":" ✓ Ready in 1254ms"}
{"level":50,"time":1752212533207,"pid":94,"hostname":"25302d92f23d","name":"console","email":"peasinapod655@gmail.com","callbackURL":"/boards?type=invite&memberPublicId=mmxh3y08jvhv","error":{"status":0,"statusText":""},"msg":"Failed to send magic link invitation:"}

```

**Comment by hjball** [comment]
I think I've fixed it, but I can't seem to replicate so please can someone pull latest and let me know

**Comment by hjball** [comment]
Has anyone had chance to test this yet? @daksteter @maltsev-gorskij @samschultzponsys

**Comment by samschultzponsys** [comment]
Sorry for the delay, I am still not sure the best way to pull logs but the weird UI behavior as well as invites not emailing are still happening to me as shown here:

![Image](https://github.com/user-attachments/assets/746ca31b-8490-45ea-b763-4fb87a24750e)

**Comment by samschultzponsys** [comment]
Ah here are my logs: [✓] migrations applied successfully!
kan-web  | > @kan/web@0.1.0 start /app/apps/web
kan-web  | > pnpm with-env next start
kan-web  | 
kan-web  | 
kan-web  | > @kan/web@0.1.0 with-env /app/apps/web
kan-web  | > dotenv -e ../../.env -- "next" "start"
kan-web  | 
kan-web  |    ▲ Next.js 15.3.4
kan-web  |    - Local:        http://localhost:3000
kan-web  |    - Network:      http://172.19.0.3:3000
kan-web  | 
kan-web  |  ✓ Starting...
kan-web  | - event [next-runtime-env] read environment variables prefixed with 'NEXT_PUBLIC_' from process.env.
kan-web  | - ready [next-runtime-env] wrote browser runtime environment variables to '/app/apps/web/public/__ENV.js'.
kan-web  | {"level":30,"time":1752518286550,"pid":98,"hostname":"1f9817fc01ab","name":"console","msg":" ✓ Ready in 1186ms"}
kan-web  | {"level":50,"time":1752520647949,"pid":98,"hostname":"1f9817fc01ab","name":"console","email":"sam.scXXXXXX@gmail.com","callbackURL":"/boards?type=invite&memberPublicId=k296652hi8xm","error":{"status":0,"statusText":""},"msg":"Failed to send magic link invitation:"}
kan-web  | {"level":50,"time":1752520711678,"pid":98,"hostname":"1f9817fc01ab","name":"console","email":"sam.scXXXXXX@gmail.com","callbackURL":"/boards?type=invite&memberPublicId=i2yn3e5dd9is","error":{"status":0,"statusText":""},"msg":"Failed to send magic link invitation:"}

**Comment by maltsev-gorskij** [comment]
> Has anyone had chance to test this yet? [@daksteter](https://github.com/daksteter) [@maltsev-gorskij](https://github.com/maltsev-gorskij) [@samschultzponsys](https://github.com/samschultzponsys)

Still can't see a clear explanation in the logs for why the link isn't sending. 
Just "Failed to send magic link invitation:" error is not enought for debug. 

```
2025-07-14T19:31:03.669801018Z ! Corepack is about to download https://registry.npmjs.org/pnpm/-/pnpm-9.14.2.tgz
2025-07-14T19:31:08.204862637Z 
2025-07-14T19:31:08.204895801Z > kan@ db:migrate /app
2025-07-14T19:31:08.204899583Z > cd packages/db && pnpm migrate
2025-07-14T19:31:08.204902377Z 
2025-07-14T19:31:09.945121781Z 
2025-07-14T19:31:09.945152629Z > @kan/db@0.1.0 migrate /app/packages/db
2025-07-14T19:31:09.945156821Z > pnpm with-env drizzle-kit migrate
2025-07-14T19:31:09.945159485Z 
2025-07-14T19:31:11.575561668Z 
2025-07-14T19:31:11.575592857Z > @kan/db@0.1.0 with-env /app/packages/db
2025-07-14T19:31:11.575607012Z > dotenv -e ../../.env -- "drizzle-kit" "migrate"
2025-07-14T19:31:11.575610103Z 
2025-07-14T19:31:12.282468783Z No config path provided, using default 'drizzle.config.ts'
2025-07-14T19:31:12.283403032Z Reading config file '/app/packages/db/drizzle.config.ts'
2025-07-14T19:31:13.280798401Z Using 'pg' driver for database querying
2025-07-14T19:31:15.153168178Z [⣷] applying migrations...[2K[1G[✓] migrations applied successfully!
2025-07-14T19:31:15.153207391Z > @kan/web@0.1.0 start /app/apps/web
2025-07-14T19:31:15.153210820Z > pnpm with-env next start
2025-07-14T19:31:15.153213510Z 
2025-07-14T19:31:16.554353988Z 
2025-07-14T19:31:16.554408933Z > @kan/web@0.1.0 with-env /app/apps/web
2025-07-14T19:31:16.554413694Z > dotenv -e ../../.env -- "next" "start"
2025-07-14T19:31:16.554416602Z 
2025-07-14T19:31:17.952192782Z    ▲ Next.js 15.3.4
2025-07-14T19:31:17.952524408Z    - Local:        http://localhost:3000
2025-07-14T19:31:17.952557410Z    - Network:      http://10.0.1.37:3000
2025-07-14T19:31:17.952650146Z 
2025-07-14T19:31:17.952686286Z  ✓ Starting...
2025-07-14T19:31:20.453118790Z - event [next-runtime-env] read environment variables prefixed with 'NEXT_PUBLIC_' from process.env.
2025-07-14T19:31:20.453980985Z - ready [next-runtime-env] wrote browser runtime environment variables to '/app/apps/web/public/__ENV.js'.
2025-07-14T19:31:21.143200009Z {"level":30,"time":1752521481142,"pid":96,"hostname":"3923a2de3658","name":"console","msg":" ✓ Ready in 4s"}
2025-07-14T19:31:48.356231541Z {"level":50,"time":1752521508355,"pid":96,"hostname":"3923a2de3658","name":"console","email":"l####@gmail.com","callbackURL":"/boards?type=invite&memberPublicId=a1zjo37hkjhq","error":{"status":0,"statusText":""},"msg":"Failed to send magic link invitation:"}
```

**Comment by hjball** [comment]
Ah it looks like I accidentally reverted my recent changes @maltsev-gorskij @samschultzponsys 

Sorry about that! Any chance you could pull latest and try again for me?

**Comment by samschultzponsys** [comment]
It did work correctly for me today, if someone else wants to test to confirm. Also once logged in with this magic link can the user establish a password, currently I have email login disabled in my instance so this may contribute to the issue. I am trying to get OIDC working to allow seamless sso login. Probably will have to do a forwarded auth through the proxy since OIDC is not natively supported currently, so I believe.

**Comment by samschultzponsys** [comment]
OOH new problem started, now with a new user when they are invited they get the email with the button, when they click it they are brought to a page asking for their email, once their email is entered it just sends them a new email and the loop starts again.

**Comment by xitriy87** [comment]
Yes, link is not working. You get link for login with enter password which not set and this is loop.

**Comment by maltsev-gorskij** [comment]
@hjball 
I got concrete smtp connection timeout error with your latest improvements to logging. So thanks. More logging are also good for debug. 

My problem was with VPS restriction to use 465 port. I'v requested permission to this port from hosting tech support and email invites are now working. 

But when i click on invite link in email and providing email and password nothing happens and invited user are still in pending status. No logs about it in Docker container though.

**Comment by maltsev-gorskij** [comment]
A little addition to my comment

Tried recently released 0.2.5 version of kan
- Generated link via members Kan section and got email
- Clicked on link and provided email, used in invitation form, and password
- Got "Invalid email or password" error

<img width="1074" height="862" alt="Image" src="https://github.com/user-attachments/assets/acff30a6-cd54-4aef-924e-e3c3f7655ba8" />

In docker container this log entry are appeared
<img width="1830" height="96" alt="Image" src="https://github.com/user-attachments/assets/300640e2-a959-4da0-8019-78183088be93" />

**Comment by hjball** [comment]
Thanks all for flagging. I'm taking a look into this as priority.

**Comment by hjball** [comment]
Fixed on latest now @maltsev-gorskij @daksteter @xitriy87
